### ISSUE TITLE
Software Citation - section addition

### ISSUE THREAD

**Issue by mrchristian** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#1]
Hi,

At the Open Science Lab I am coordinating examination of the topic of 'Software Citation' as an editorial theme to run over May 2018 on a new Open Science Platform. OSL: https://www.tib.eu/en/research-development/open-science/

We can offer to add information on the subject of 'Software Citation'.

We are asking community members to make blog contributions, take part in discussion, create how-tos (or pointers to existing help resources).

The topic is outlined here https://wiki.tib.eu/confluence/display/osp/Theme%3A+Software+Citation

The FORCE11 Software Citation working groups give a good basis for understanding the topic, especially the paper Software Citation Principles (very big tip of hat):

Smith, Arfon M., Daniel S. Katz, and Kyle E. Niemeyer. ‘Software Citation Principles’. PeerJ Computer Science 2 (19 September 2016): e86. https://doi.org/10/bw3g.

Thanks

Simon Worthington - Open Science Lab
TIB – German National Library of Science and Technology

**Comment by Protohedgehog** [comment]
Hi Simon,

Sorry for taking so long to get back to you on this! The [software citation sub-section](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.md#software-citation-) now has content!  Imagine that. I'll keep working on this too, but feel free to use any of what is here if needed, or contribute your own wisdom! :)

Cheers,
Jon

**Comment by mrchristian** [comment]
Hi J,

Good one. I get the idea that the sub-section is everything under the single H2 header. Ill get to work on listing the headline issues and then look how to bring them across to the MOOC.

S

**Comment by Protohedgehog** [comment]
Fantastic, thank you Simon!
