### ISSUE TITLE
Question about 'existing platforms and tools for Open Source Software' section

### ISSUE THREAD

**Issue by arfon** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#15]
> ## Existing platforms and tools for Open Source Software
> Virtual environments and machines are becoming increasingly popular as high-powered research workflow enablers. Popular services include Google Cloud and Amazon Web Services, which also assist with database storage and content delivery, as well as computational power. InsideDNA is a computing platform for reproducible research in bioinformatics, genomics and the life sciences.

This [first paragraph](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.md#Platforms) reads a little strangely to me and it's not clear how it's connected to the Open Source topic area. A couple of things you could be trying to say here:

1. Virtual environments and machines are becoming increasingly popular as high-powered research workflow enablers and many of these are _built_ upon open source software (operating systems, programming languages, data processing frameworks etc.)
2. Popular services include Google Cloud and Amazon Web Services, which also assist with database storage and content delivery, as well as computational power provide a great venue for running your open source software.
3. Something else?

**Comment by Protohedgehog** [comment]
Hey Arfon, thanks for this comment. Yes, you're right, that is a bit messy. Number 1 nailed it - have edited that in now, thank you. Shockingly, we don't get taught much about OSS in Palaeontology, so writing all of this has been a huge learning curve for me too! :)
