### ISSUE TITLE
Credit for your work 

### ISSUE THREAD

**Issue by arfon** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#17]
👋 @Protohedgehog - it looks like GitHub doesn't know about the email address (`jon.tennant.2gmail.com`) you're committing changes with to this repo. This means that the commit history looks like this:

<img width="478" alt="cat" src="https://user-images.githubusercontent.com/4483/41916454-12ed455e-7926-11e8-8a12-b3ca41d3612b.png">

If you want to fix this, just add this email address to your GitHub profile: https://help.github.com/articles/adding-an-email-address-to-your-github-account/

**Comment by Protohedgehog** [comment]
Huh, that's weird. It's there in my profile, and I didn't change anything. Maybe it's because I'm doing this from R Studio and using Git from my laptop, and ther's something broken there..

**Comment by arfon** [comment]
Weird indeed... Not sure what's going on there then!

**Comment by Protohedgehog** [comment]
![9fa](https://user-images.githubusercontent.com/4954131/41917129-f1cd4b60-7959-11e8-8a23-99e131bdfdcb.gif)

I have an idea..
