### ISSUE TITLE
PLOS Open Source Toolkit

### ISSUE THREAD

**Issue by NathanielPLOS** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#2]
A potentially useful resource: https://channels.plos.org/open-source-toolkit 

The Open Source Toolkit features articles and online projects describing hardware and software that can be used in a research and/or science education settings across different fields, from basic to applied research. The Channel Editors aim to showcase how open source tools can lead to innovation, democratization and increased reproducibility.

Channel Editors select content from PLOS journals and also highlight articles from the broader literature. Additional resources such as open source projects, preprints, information about repositories and policy discussions that are deemed of particular interest are also featured.

If you have already published your open source research at PLOS or elsewhere and would like to see it featured in the Open Source Toolkit please email channels@plos.org and your paper will be sent to the Channel Editors for consideration, or tweet us @PLOSChannels with the hashtag #PLOSOpenSource

Thanks,

Nathaniel

**Comment by Protohedgehog** [comment]
Hey Nathaniel,

Sorry for taking so long to get back to you about this. The content production for this is now well on the way [here](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.md#software-citation-), and I would love for any contributions you might have to offer! :)

Cheers,

Jon

**Comment by Protohedgehog** [comment]
Added this as a resource now
