### ISSUE TITLE
Bold for emphasis?

### ISSUE THREAD

**Issue by mrchristian** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#21]
I notice bolding isn't being used for emphasis.

For web reading its a good idea to use it to facilitate scan reading, see:

Nielsen, Jakob. 1997. ‘How Users Read on the Web’. Nielsen Norman Group (blog). 1 October 1997. https://www.nngroup.com/articles/how-users-read-on-the-web/.

I would suggest a style guide is added.

For the existing module or complete MOOC it would make sense for this to be done in bulk copy editing sweeps.

Simon

**Comment by Protohedgehog** [comment]
I noticed too that you used the > in some places to create little quote-like boxes. Are there any other little things like that we can do to break up the text? Images still to come..

**Comment by jcolomb** [comment]
Another way is to insert code with 

```
Boxed text
```

I think it is the only 2 options in markdown (?)

Am 27. Juli 2018 12:57:03 MESZ schrieb Jon Tennant <notifications@github.com>:
>I noticed too that you used the > in some places to create little
>quote-like boxes. Are there any other little things like that we can do
>to break up the text? Images still to come.. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/issues/21#issuecomment-408385331

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Protohedgehog** [comment]
This is awesome @jcolomb, thanks! Do you think this could be added somehow? Maybe something like a task on how to learn the basic Git commands..?

**Comment by pcmasuzzo** [comment]
I think some (basic and non) Git commands can be added indeed with the insert code style. 
I have not had a lot of time on my hands recently, but I will try to open a PR soon.

**Comment by tosteiner** [comment]
There's a lot that Git-flavoured Markdown can do re: text structuring (and it helps to learn these by heart in order to be free from the editor's visual aids 😉 ). 

* **Code blocks** via ` ``` `, as mentionend in https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/issues/21#issuecomment-408438450, including syntax highlighting: https://help.github.com/articles/creating-and-highlighting-code-blocks/
* **Quotes** via the bracket `>`-symbol that Jon mentioned, see https://help.github.com/articles/basic-writing-and-formatting-syntax/ 
* so-called **"thematic breaks"** like with html-`<hr>`s usually work via adding `---` in a separate line
* and, of course, **lists** (unnumbered, numbered, nested) - https://help.github.com/articles/basic-writing-and-formatting-syntax/#lists

**Comment by Protohedgehog** [comment]
Awesome, thanks @pcmasuzzo and @tosteiner! Atm there aren't any explicit code blocks, but if there is scope to add them this could be cool. It might be nice to have something as an optional extra task?

**Comment by Protohedgehog** [comment]
How do you folks things are looking now after a wave of formatting updates? :)  @mrchristian

**Comment by Protohedgehog** [comment]
@tosteiner @mrchristian Do you think the main body text is looking better now?

**Comment by Protohedgehog** [comment]
Ping @tosteiner @mrchristian @pcmasuzzo @jcolomb - Does this need more jazzing up still in terms of style? The whole thing has been significantly changed recently. https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.md

**Comment by tosteiner** [comment]
@Protohedgehog looks awesome, brilliant! 👍
