### ISSUE TITLE
authors in Zenodo

### ISSUE THREAD

**Issue by mrchristian** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#24]
Hi,

We need clarification about where authors are derived from in Zenodo when importing a GitHub repo. Is it from the GitHub user account, or is it from the CONTRIBUTOR file.

Also note in Zenodo you can add authors.

I could test out where the authors are derived from but if someone has the answer that will be easier.

When we have clarification I'll edit para.

Simon

**Comment by mrchristian** [comment]
Hi,

I raised a ticket on this with Zenodo/OpenAIRE as it can become a little nuanced (what a surprise).

QUOTE:
Reference | 01251-2018-07-21

Hi,
I'm writing documentation on submitting GitHub repositories for researchers to Zenodo and I need help on how Zenodo gets author information from GitHub. 

1. Is it a. from the GitHub user names, or b. from a CONTRIBUTOR or other metadata file in the repo.

Also

2. Do the release versions inherit the author names from the 'concept submission' or from the names in the GitHub repository at the time of release submission.

Many thanks

Simon

END QUOTE

Zenodo have DOI model of (with each DOI having its own editable metadata) - eek, problemo?

v1.0 (specific version): 10.5281/zenodo.60943
v1.1 (specific version): 10.5281/zenodo.800648
Concept (all versions): 10.5281/zenodo.705645

http://help.zenodo.org/

S

**Comment by katrinleinweber** [comment]
> Is it from the GitHub user account, or is it from the CONTRIBUTOR file.

Definitely (also) from the Git history. I am "co-author" of several Zenodo records, to whose source repo on GitHub I contributed.

Funnily enough, the person with the fewest lines touched (as counted by Git) is in the last position. Some disciplines recognize this as senior author ;->

**Comment by mrchristian** [comment]
Hi,

Ah great thank you. Interesting how the attribution is getting assigned, defo appears that it needs some further systemization. One typo update and I'm senior author ;-).

**Comment by katrinleinweber** [comment]
Only to those who enjoy navel-gazing and tea-leaf-reading more than actual data & its processing ;-D Attribution is hard, and thus any effort is better invested in _con_-tribution.
