### ISSUE TITLE
previewing local MD files

### ISSUE THREAD

**Issue by mrchristian** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#26]
Hi,

Do people have a suggestion for previewing local GitHub version of .md markdown files.

I've found this, looks interesting. But don't want to waste time testing pipeline if people have a better tried and tested workflow.

https://github.com/dmarcotte/github-markdown-preview

Simon

**Comment by jcolomb** [comment]
Rstudio has a preview button and does work smoothly with github.

Am 22. Juli 2018 13:50:00 MESZ schrieb Simon Worthington <notifications@github.com>:
>Hi,
>
>Do people have a suggestion for previewing local GitHub version of .md
>markdown files.
>
>I've found this, looks interesting. But don't want to waste time
>testing pipeline if people have a better tried and tested workflow.
>
>https://github.com/dmarcotte/github-markdown-preview
>
>Simon
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/issues/26

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mrchristian** [comment]
FAB, I'll give it a shot :-)

**Comment by mrchristian** [comment]
Hi,

I thought about going for a lighter options for local md previewing. First I tried some Chrome browser plugins, no good, didn't work. But then I figured, eureka, Atom editor must have a preview renderer, and sure enough it does, and its great.

https://atom.io/packages/markdown-preview

NB: Atom also intergrates into Git very nicely, like other good text editor, so you can do all your usual Git command straight from your editing interface.

https://atom.io/
![md_preview](https://user-images.githubusercontent.com/772579/43047358-7597f838-8dd6-11e8-9fb4-eb8e96173026.jpg)


S

**Comment by Protohedgehog** [comment]
That's good to know, thanks!  I've been using RStudio as Julien mentioned too, and that seems to work nicely.
