### ISSUE TITLE
External Links

### ISSUE THREAD

**Issue by lmatthia** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#28]
It would be great external links would open in a new tab, automatically. For the markdown version, opening links in a new tab works with ctrl+click, but it doesn't work in the Python version. This can probably be fixed by tweaking the html but as below this might need another fix as well.

Also, internal links (Table of Contents) don't seem to work in the Python version. This is probably because of the conversion not working with html.

**Comment by Protohedgehog** [comment]
This seems to have been fixed now by using an alternative to the GitHub viewer.
