### ISSUE TITLE
mention alternative to github-zenodo

### ISSUE THREAD

**Issue by jcolomb** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#29]
At the moment, content focus on the github-zenodo integration and worflow.

It seems to me that the content is not software specific. I have a non software project (rdmpromotion.rbind.io) which follows the github-zenodo scheme. Other topics should come forward (write code for re-use, docking, liscences, ....)

On the other hand, focusing on one tool is not the way I would like to see this going. The principles are more important. In 2 years from now, a gitlab/figshare worflow may exist and be better (who knows?). But the principles of a version controlled platform allowing collaboration for development and backup + a repository for long term storage and citation will still be there(?). (BTW, zenodo gives no garantee about how long the storage will be (I think) such that other repositories may be more usefull.) So it should be clear that the tasks are examples (even if that's the easiest way to go at the moment).

I am too early for these comments?

**Comment by Protohedgehog** [comment]
Julien, if we focus on every tool available, or a wider selection of comparative tools, then this has two impacts. It makes the course less precise and focused, while potentially confusing users. It also adds a large amount of work on our end.

However, if there were additional steps to the workflow that might make nice tasks, what do you suggest? Explaining the principles is not the sort of thing that belongs in a practical activity, and #8 is about who to film, which can include discussion of the principles - also in the main content. If more can be added here too, please do add some! But yes, also it should be made clear that the tasks are just examples of the whole open source spectra of possibilities. Danke!

**Comment by Protohedgehog** [comment]
Hey @jcolomb! Does this new task help with this issue a bit? :) https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_3.md

**Comment by Protohedgehog** [comment]
@jcolomb - @dannycolin suggested doing a GitLab workflow too for this, to have an 'open alternative' to GitHub. Do you think that would help this issue?

**Comment by dannycolin** [comment]
FYI, there's also this issue [#18](https://github.com/OpenScienceMOOC/Main/issues/18) in the Main repository.

**Comment by jcolomb** [comment]
I close this, I think merge #61 solve the issue
