### ISSUE TITLE
software citation learning outcome

### ISSUE THREAD

**Issue by danielskatz** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#3]
I would like to suggest a learning outcome:

- Software developers will be able to make their software citable, and software users will understand how to cite the software they use.

**Comment by Protohedgehog** [comment]
Suggestion approved, feel free to pop it in there! :)

**Comment by danielskatz** [comment]
Will do, but I don't really have time to do the work of explaining how this will be achieved.

**Comment by Protohedgehog** [comment]
That's cool, just the learning outcome will do for now. We'll find a way to channel you into the course by proxy..

**Comment by danielskatz** [comment]
tied to #1 
can be closed when/if https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/pull/4 is merged
