### ISSUE TITLE
Links and images not converting correctly

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#30]
When I use notedown to convert the markdown files to ipynb format, the links and images appear to break and not be rendered correctly.

Compare https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.ipynb to

https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.md

Anyone know why this might be and how to fix it?

**Comment by rijdho** [comment]
add this to the end of the path: ?raw=true

 ![Open Source vs. Closed Source](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/images/open_research_software_open_source.png?raw=true)

works?

**Comment by zuphilip** [comment]
The parameters `src` and `width` should be insides "..." which in the ipynb must be escaped, because each line already starts and stops with a ". Together with the hint from above this then should work.

**Comment by Protohedgehog** [comment]
YES! Thank you both. This is the correct syntax that seems to work in both md and ipynb now:

    "<img src=\"https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/images/open_research_software_open_source.png?raw=true\" width=\"800\" />\n",

Gonna go through and fix these now, and pray that it works..

**Comment by Protohedgehog** [comment]
In Anakin voice: "It's working... it's working..!!' Thanks all :)

Any suggestions for the broken links?

**Comment by zuphilip** [comment]
> Any suggestions for the broken links?

AFAIS the absolute links work and only the relative links don't work. Or any other problem?

**Comment by Protohedgehog** [comment]
Yes, @zuphilip, you're right sorry, should have been clearer. It is in the internal/relative links that don't seem to work - the TOC, for example.

**Comment by zuphilip** [comment]
The code looks fine and when I open the IPython Notebook with another viewer it seems to work fine, e.g. http://nbviewer.jupyter.org/github/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.ipynb#What_OSS . Thus, I guess this is a problem with the viewer for `.ipynb` on GitHub itself. Maybe you can contact them and ask (from my experience I can say that they are very friendly and helpful).

**Comment by Protohedgehog** [comment]
@zuphilip OK, this is awesome news! I just checked too and found the same too - whew! Gonna close this one now :)

I'll make sure to add a comment about this too in the README file.
