### ISSUE TITLE
Design a quiz

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#32]
https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/04-quizzes.md

**Comment by Protohedgehog** [comment]
@jcolomb I think we still need to do this. Any idea for good questions to ask to start things off?

**Comment by tosteiner** [comment]
@Protohedgehog Sorry for dropping in on this - how about doing sth along the lines of https://theconversation.com/research-transparency-5-questions-about-open-science-answered-76851 to start things off? 

And for the technical aspects on how to actually do quiz modules, I can fully recommend [H5P](https://h5p.org/), an amazing open source project based in Norway - see https://h5p.org/content-types-and-applications on what it can do ✨

**Comment by Protohedgehog** [comment]
Hey @tosteiner, this looks pretty cool. If we do it here, we have plenty of choices too: https://eliademy.com/app/a/quizzes/new/02d7338a7e Happy to add you as an instructor/admin if you like? Or we can flesh it out in the md file above and then integrate after. Also, greetings from Norway! :)

**Comment by tosteiner** [comment]
@Protohedgehog wow, eliademy also looks great, yes! What I particularly like about H5P is the fact that you can self-host it via your own WordPress blog, so no need for external accounts, but I suppose this is more of a philosophical thing re: control of one's data ;) Anyhow, and off-topic: You're currently visiting Norway? Didn't you just spend the Summer in Bali? Man, you sure are travelling the world! 😎

**Comment by Protohedgehog** [comment]
Man, you do not want to know my travel schedule the last couple of months.. Croatia, Brazil, Bali, Taiwan, Canada, France, Germany, US.. I need a sabbatical ;) Currently up in Tromso, just arrived for the Munin conference! 

And yes, the quiz! It needs to be integrated into the MOOC itself, which is the appeal of the above. Hope the link worked.

**Comment by tosteiner** [comment]
Oh, Tromso, I see - nice! might well be that you run into Oliver Tacke (He's one of the H5P guys) - if so, make sure to say hi, he's a great guy! 😉  

and yup, back to the quiz: link works, yes - i've now registered a profile (info@flavoursofopen...) - would be great if you could add me as instructor, I'll then see what I can come up with 👍 Also, enjoy the Munin conference!

**Comment by Protohedgehog** [comment]
OK, just waiting for that to come into the system then will upgrade you! 

Thanks, will keep a look out for Oliver too :)

**Comment by gedankenstuecke** [comment]
Please say hi to Oliver from me too if you run into him! 👋

**Comment by Protohedgehog** [comment]
Hi folks, I'd like to get a quiz set up here shortly if possible: https://eliademy.com/app/a/quizzes/new/02d7338a7e (Lemme know if you want me to add you as an instructor, @tosteiner @gedankenstuecke @jcolomb)

Any thoughts on example questions? I can add multiple choice, true/false, or open ones. :)

**Comment by tosteiner** [comment]
@Protohedgehog yup, instructor mode would be great, my registered email is `...favoursofopen...`

am currently tied down with other stuff, but will try to come up w. a few sample questions later today (evening)

**Comment by Protohedgehog** [comment]
OK, upgraded @tosteiner! And yep, no rush. We can brainstorm [things together here too](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/04-quizzes.md) if you want.

**Comment by tosteiner** [comment]
@Protohedgehog surprisingly found myself with a little bit of time available (cancelled meeting), so here's some suggestions: [04-quizzes.md](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/04-quizzes.md)

**Comment by Protohedgehog** [comment]
Yes, these are so awesome! I left a comment on the PR [here](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/pull/48#issuecomment-444117294).

I love this so much, but think it would be more applicable to the module on OA?

**Comment by Protohedgehog** [comment]
Got the new PR @tosteiner, so awesome! Can I go ahead and integrate these into the MOOC platform right away? :)

**Comment by tosteiner** [comment]
@Protohedgehog sure, no problem

**Comment by tosteiner** [comment]
@Protohedgehog btw... you still looking for collaborators for the open access/open source article you mentioned on twitter a few days ago?

**Comment by Protohedgehog** [comment]
@tosteiner pinged on Twitter.

Also, it should be live here now any time! https://eliademy.com/app/a/courses/02d7338a7e/tasks

**Comment by tosteiner** [comment]
@Protohedgehog nice, thanks! Re: eliademy quiz- yup, it's there, but explanations are missing - did you copy those in as well?

**Comment by Protohedgehog** [comment]
Yeah, they should be there. It's going live in 2 minutes. Maybe they only show up once you've selected an answer and submitted? Feel free to take it for a totally unbiased test swing ;)

**Comment by tosteiner** [comment]
🤷‍♂️ nope, only displaying the actual results... see img [1](https://user-images.githubusercontent.com/41517607/49462913-8a0eab00-f7f7-11e8-9473-791ec977a080.PNG) and [2](https://user-images.githubusercontent.com/41517607/49462888-7e22e900-f7f7-11e8-95b2-1534b2020297.PNG)

**Comment by Protohedgehog** [comment]
OK, first of all, how did you get questions from a quiz you designed wrong? ;)

And let me look into it, as that is weird.

**Comment by tosteiner** [comment]
> OK, first of all, how did you get questions from a quiz you designed wrong? ;)
 
totally unbiased test swing ftw 😎

**Comment by Protohedgehog** [comment]
Can you try submiting it? Perhaps that triggers something on my end to share the feedback.

**Comment by tosteiner** [comment]
done

**Comment by Protohedgehog** [comment]
Hm, weird. On my end, I can view your answers, and the explanations come up. I reset it now. Maybe the explanations only come up once you get 100% too, otherwise it gives away the answers for future attempts? I reset your result too btw ;)

**Comment by Protohedgehog** [comment]
OK @tosteiner I figured this out. It does show up, once you have reviewed and submitted. You then click the review answers button and it shows up with all the additional explanatory text!

So, time to go live :)
