### ISSUE TITLE
Design screencast recordings

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#33]
Using OBS Studio: https://obsproject.com/

Design screen recordings to accompany Task 1 and Task 2. 

Exra: Make sure scripts are written and can be used for subtitles, including translation into non-English languages.

**Comment by Protohedgehog** [comment]
Note: Slight delay on this issue because my microphone sucks and I have to purchase a new one.

**Comment by Protohedgehog** [comment]
The first one of these is now online: https://www.youtube.com/watch?v=AnftV9HBPSc

**Comment by bapalmer** [comment]
Sound quality could be improved on. Difficult to hear with my headphones on, but OK when using the laptop speakers.

I used the MOOC-Module-5 (Tasks 1-3) as a basis to a 1 hour intro to Git/GitHub and RStudio at an Open Science workshop here in Cork last week. Very clear walk-through. Zero issues with respect to linking the two. Might suggest a bit more emphasis on the Git button that appears in the RStudio toolbar. Nice feature for those who fear command line!

**Comment by Protohedgehog** [comment]
Awesome, thanks for the feedback, @bapalmer! I'll make sure the quality is higher next time, not sure what happened there, maybe an issue with the file conversion/editing software. I used a pretty good mic for it.

Super glad that you used some of the material too, thank you!! Could you perhaps add some suggestions on how we could integrate more about the Git button [here](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_3.md)? and then I can make sure to integrate that into the screencast too? :)

**Comment by dannycolin** [comment]
Eh @Protohedgehog out of curiosity what's the model of your mic?

**Comment by Protohedgehog** [comment]
I don't have it with me right now, @dannycolin, but I think it's the Samson Meteor.

**Comment by bapalmer** [comment]
[Here are my slides](https://github.com/bapalmer/reproducible-workflows/blob/master/afternoon_session/docs/2018-11-01_Github_to_RStudio.pdf) from a talk I gave to R users new to git/GitHub. 

I plan on giving it again soon, so what I'll do is add in some slides using the Git button, see how it goes and get back to you.

**Comment by Protohedgehog** [comment]
That's awesome, thanks @bapalmer! I'll have a look too, as I was planning on doing the screen recording for this one in the next couple of weeks.

**Comment by Protohedgehog** [comment]
Heads up @bapalmer, the 'next couple of weeks' thing fell through due to travels, but I expect still maybe to have this done in the next week or so, time pending again (more travels). Any feedback on the Git button addition for now would be super! :)

**Comment by bapalmer** [comment]
I'll play around with it over the next day and let you know. I got a little side-tracked myself as I look to host some regular #openscience demos during lunch at my institution. First one was research organisation through R-projects (https://github.com/bapalmer/lunchtime_sessions). 

Part 2 will be R Markdown, Part 3 is git/GitHub and part 4 will be using OSF to package the workflows as a final step towards FAIR for the researcher who has R in their back-pocket, but little else. If I can pull it together like it looks in my mind, it might be worth suggesting it as a workshop at the Royal Statistical Society in Belfast next September.

**Comment by Protohedgehog** [comment]
This all sounds awesome, @bapalmer, thanks! I wonder if some of the stuff on markdown could also be added here? https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/Task_1.md#markdown

We'll also be doing an OSF bit later on in the modules, and have a very short intro to them here too for now, which might be useful: https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/Task_2.md#osf

**Comment by Protohedgehog** [comment]
The next one of these is now online, for linking between Zenodo and GitHub! https://www.youtube.com/watch?v=pjsbBQYOOaE&t=7s

**Comment by Protohedgehog** [comment]
And the next is now live too! https://www.youtube.com/watch?v=Q-6jfjSAspA&feature=youtu.be

All three have been integrated into the main platform now too. https://eliademy.com/catalog/catalog/product/view/sku/02d7338a7e
