### ISSUE TITLE
New task: Linking Git and GitHub with R

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#38]
Thoughts on making a new task for this? Plenty of resources out there already to draw from, eg: http://happygitwithr.com/

**Comment by Protohedgehog** [comment]
First stab at this is now ready for feedback: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_3.md @jcolomb @rvosa @mrchristian @pcmasuzzo @trallard and co! :)

**Comment by Protohedgehog** [comment]
Did anyone have a chance to have a look at this just yet? :)

**Comment by jcolomb** [comment]
just checking. 

I personally do not know what FOSS is, if you want to start by stating vocabularies they should know of, add links to their definition.
1. I think gif is pronounced "dj" not "g" ??
2. the phd comics visual: coüyrighted material, did you get an written consent that you can use it?
3. I normally download the github desktop client to get the latest git. It is also nice to have some way to use more powerful git commands (I use sourcetree on the mac): when there are git problems, Rstudio is not helping much (merging problems, git reset,... )

to be continued...

**Comment by Protohedgehog** [comment]
So, have you read through the main text then yet @jcolomb? It goes through all of this in there, with the intention being that these things are done sequentially. I didn't get explicit permission from Jorge - what do you mean 'coprighted', as in no reuse without permissions in this context).

Awesome re the Git commands. Feel free to add some more basic ones in. I still use the bash terminal for most things too, as I've found when you try and do some commands in the Rstudio terminal it can't distinguish between the wider platform and Git. Like typing ctrl-o won't write out a Git commit, but try and open a file in Rstudio instead. Annoying..

**Comment by jcolomb** [comment]
sorry for the misspelling, indeed phd comics are not distributed under a permissive license, you need to ask permission.

I do use the commit and push buttons in Rstudio, they work perfectly fine for me. why going to the shell to do that?
I also not do "git add .", the commit functions of Rstudio are doing the add when I commit.

Any remarks form professional coders ?

In general, I find it a bit too complicated. Of course, I do not remember the setup of git, as I did that so much time ago, but I feel it could be simplified. Please be inclusive of mac users, your jokes are keeping us out of your community. (In addition, the mac terminal is a great way to use commands (git, dat,...) , also allowing easy install of a lot of application via homebrew...).

In brief, I use Rstudio to git commit, git pull and git push. For other functions, I use sourcetree (merge) or the shell (setup git user, git reset, anything else I have to google to solve).

I realise that there is no task about git itself, or version control in general. This makes this part very tricky to follow.
...

**Comment by jcolomb** [comment]
I will try to take some time this week to make changes on a different branch.

**Comment by Protohedgehog** [comment]
OK, I'll make sure to ask them. Or simply remove it then.. 

Sorry, the buttons work fine, but if you use the terminal inside Rstudio to make commands, then it gets weird sometimes.

Do you think a new task like intro to Git/VC is needed? That would be quite a bit more work..

**Comment by Protohedgehog** [comment]
Ping @jcolomb for any possible updates on this? :)

**Comment by Protohedgehog** [comment]
Hey @jcolomb, any updates on this by any chance? Issue #33 also has some comments on this now about adding more with the Git button in RStudio.
