### ISSUE TITLE
quizz

### ISSUE THREAD

**Issue by jcolomb** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#59]
all right answers are `false` maybe we could rephrase some... I think we could go to 20 questions with more technical aspects to it ?

**Comment by Protohedgehog** [comment]
CC @tosteiner

**Comment by tosteiner** [comment]
@jcolomb @Protohedgehog am right on it :) Here's a few more plus updated ones 

https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/pull/62

More suggestions, topics & whole questions always welcome 😉

**Comment by Protohedgehog** [comment]
Ahhh, these are excellent @tosteiner, but it seems the quiz can't be updated with new questions now that people have started completing it! Maybe I could add a second quiz?

**Comment by Protohedgehog** [comment]
@jcolomb @tosteiner thoughts on adding a second quiz?

**Comment by tosteiner** [comment]
@Protohedgehog whoopsey, sorry, I didn't comment earlier because I took that as a given 😉 sure, how about I set this up right away in eliademy, with the new set of questions?

**Comment by Protohedgehog** [comment]
If you have access @tosteiner, go for it! That would be awesome.

**Comment by tosteiner** [comment]
@Protohedgehog hm, looks like I'm missing instructor rights for https://eliademy.com/app/a/courses/02d7338a7e - could you please add me?

**Comment by Protohedgehog** [comment]
That is a travesty.. Allow me to fix asap!

**Comment by Protohedgehog** [comment]
I just gave you admin rights now @tosteiner

**Comment by tosteiner** [comment]
@Protohedgehog fabulous, thank you - looks like it's working now, ta!

**Comment by tosteiner** [comment]
@Protohedgehog darn, sorry to keep bugging you with this - could you try this 

http://helpdesk.eliademy.com/knowledgebase/articles/669763-how-to-add-another-teacher-to-a-course-co-teacher

for Module 5? Looks like I don't need to be admin, but be able to change the specific course content/design so as to add a quiz....

**Comment by Protohedgehog** [comment]
Done!

**Comment by tosteiner** [comment]
fab! thanks!

**Comment by tosteiner** [comment]
@Protohedgehog it hath been done! Have a peek here: https://eliademy.com/app/a/aquizzes/825226

**Comment by Protohedgehog** [comment]
Wow, @tosteiner, this is absolutely amazing! And live in a month or so, right? Feel free to release it whenever you want. You can also message all the participants too about it, if you wish!

**Comment by tosteiner** [comment]
yeah, the going-live date was just perfunctory in order to get things set up ...

One thing that I'm not sure about: do we want to replace the "old" one with this one, then? Would of course mean that getting that certificate is more difficult 😉

**Comment by tosteiner** [comment]
@Protohedgehog okay, so I've set this now to go live tomorrow at noon, and labeled it as a Bonus Quiz set for those eager to further test their knowledge ;)

**Comment by Protohedgehog** [comment]
Awesome, nice work @tosteiner! It looks like people are completing it already :)

**Comment by tosteiner** [comment]
👍 excellent! @Protohedgehog @jcolomb okay if we close this here for the moment? The quiz set can regularly be updated, of course ... (didn't come up with 20 questions as suggested [above](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/issues/59#issue-397441447), though - atm we're at ten 😉 )

**Comment by Protohedgehog** [comment]
I think it should be okay to close this for now @tosteiner
