### ISSUE TITLE
Finish task 1, create a GitHub repository

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#6]
Development here: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_1.md

**Comment by Protohedgehog** [comment]
This has now been completed, but I will leave it open as any feedback on the Task would be greatly appreciated.

**Comment by lmatthia** [comment]
Under "The foundational steps", right at the end, it would be good to list the file names as you commonly use them. The explanation was clear, but, as a total noob, I still asked myself "Is this how you do it?" and I also would've labeled the files as they were listed before (e.g., CONTRIBUTING_GUIDELINES). Probably not wrong but less common I assume?!

**Comment by Protohedgehog** [comment]
OK, this has been updated now: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_1.md#the-foundational-steps-

Thanks! :)
