### ISSUE TITLE
hyperlinks need to be corrected

### ISSUE THREAD

**Issue by jcolomb** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#65]
fail for: 
main.md:
https://open-science-training-handbook.gitbook.io/book/es/02opensciencebasics/03openresearchsoftwareandopensource#knowledge
```
task2:
https://www.linuxfoundation.org/blog/10-years-of-git-an-interview-with-git-creator-linus-torvalds/
```
o1-plan.md:
http://www.digitalfreedomfoundation.org/
design:
http://datascienceassn.org/sites/default/files/The%2520Scientific%2520Method%2520in%2520Practice%2520-%2520Reproducibility%2520in%2520the%2520Computational%2520Sciences.pdf
quizz:
https://en.wikipedia.org/wiki/GNU_General_Public_Licensen
keaelenments:
http://datascienceassn.org/sites/default/files/The%2520Scientific%2520Method%2520in%2520Practice%2520-%2520Reproducibility%2520in%2520the%2520Computational%2520Sciences.pdf 
https://cloud.google.com/compute/)(GCE)%2c
module design protocol:
1. [L011] 404 https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Ope  
  2. [L012] 404 https://github.com/OpenScienceMOOC/Module-6-Open-Access-to-Resea  
  3. [L030] 404 https://opensciencemooc.eu/proposed-modules/  
  4. [L037] 404 https://opensciencemooc.eu/about-us/production-team/ 
contribute:
https://twitter.com/OpenSci_MOOC

_Originally posted by @jcolomb in https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/pull/64/comment#issuecomment-453047942_

**Comment by jcolomb** [comment]
Who want to assign himself ?

**Comment by jcolomb** [comment]
task2 done (actually the error was in task 1, sorry for that mistake).

**Comment by Protohedgehog** [comment]
OK, fixed all this now in the latest commit. Thanks @jcolomb!

**Comment by jcolomb** [comment]
only one was corrected !

**Comment by jcolomb** [comment]
sorry did not see you did it, checking now...

**Comment by Protohedgehog** [comment]
You sure? I fixed quite a few, all those mentioned above.

**Comment by jcolomb** [comment]
one of them was missing: OpenScienceMOOC is our twitter account, all good now!
