### ISSUE TITLE
https://openmoocers-slackin.herokuapp.com/  link broken

### ISSUE THREAD

**Issue by jcolomb** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#74]
if this is the rigth link, herokapp is down
(application error)

**Comment by Protohedgehog** [comment]
Nope, it broke, so had to rebuild to: https://osmooc.herokuapp.com/

Where did you find that link? Need to make sure they're replaced.

**Comment by jcolomb** [comment]
It is everywhere... https://travis-ci.org/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/builds/490508222?utm_source=github_status&utm_medium=notification

**Comment by Protohedgehog** [comment]
In the GH files, yes, perhaps still. Can you pinpoint where @jcolomb? I've fixed virtually all on Eliademy itself.

**Comment by jcolomb** [comment]
I am on it, will pull request later.

**Comment by Protohedgehog** [comment]
Perfect, thanks @jcolomb!

**Comment by jcolomb** [comment]
This was fixed, #77 
I also needed to change one folder name:**never use spaces in folder or filenames !!!!**
